# -*- coding: utf-8 -*-
"""Pertemuan 2 daa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sr175mNV8leITOIdkXoSOZ41YTEKWrd0
"""

import numpy as np

# terdapat list a dan b
a = [1, 2, 3]
b = [4, 5, 6]

# lalu jumlahkan
hasil = a + b
print(hasil)

def add(list_a, list_b):
    result = []
    for first, second in zip(list_a, list_b):
        result.append(first + second)
    return result

a = [1, 2, 3]
b = [4, 5, 6]

print(a)
print(b)
print(add(a, b))

import numpy as np

# membuat array
nilai_siswa = np.array([85, 55, 40, 90])
# mengakses data pada array
print(nilai_siswa[3])

import numpy as np

print(np.__version__)

print("Hello, World!")
print("Nama saya (isi nama)")
print("NIM saya (isi NIM)")

print("Hello, World!")

# minta input dari user
nama = input("Masukkan nama Anda: ")
nim = input("Masukkan NIM Anda: ")

# tampilkan hasil
print("Nama saya", nama)
print("NIM saya", nim)

if 5 > 2:
    print("Five is greater than two!")

x = 5
y = "John"
print(x)
print(y)

x = 4
x = "Sally"
print(x)

# Fungsi mengambil elemen pertama
def getFirst(myList):
    return myList[0]

# Fungsi mengambil elemen kedua
def getSecond(myList):
    return myList[1]

# Fungsi mengambil elemen terakhir
def getLast(myList):
    return myList[-1]

# Uji coba
myList = [1, 2, 3, 4, 5, 6]

print("First:", getFirst(myList))    # Output: 1
print("Second:", getSecond(myList))  # Output: 2
print("Last:", getLast(myList))      # Output: 6

def getSum(myList):
    total = 0
    for i in myList:
        total += i
    return total

def getKali(myList):
    hasil = 1
    for i in myList:
        hasil *= i
    return hasil

def getBagi(myList):
    if len(myList) == 0:
        return None
    hasil = myList[0]
    for i in myList[1:]:
        hasil /= i
    return hasil

angka = [1, 2, 3, 4]

print("Jumlah (getSum):", getSum(angka))   # 10
print("Kali (getKali):", getKali(angka))   # 24
print("Bagi (getBagi):", getBagi(angka))   # 1 / 2 / 3 / 4 = 0.041666...

def getSum(myList):
    total = 0
    for row in myList:
        for item in row:
            total += item
    return total

def getBagi2(setA, setB):
    sumA = getSum([setA])
    sumB = getSum([setB])
    if sumB == 0:   # supaya tidak error bagi 0
        return None
    return sumA / sumB

def getKurang2(setA, setB):
    sumA = getSum([setA])
    sumB = getSum([setB])
    return sumA - sumB

set1 = [1, 2, 3]
set2 = [4, 5, 6]

print("Jumlah set1:", getSum([set1]))  # 6
print("Jumlah set2:", getSum([set2]))  # 15

print("Hasil Bagi set1 / set2:", getBagi2(set1, set2))   # 6 / 15 = 0.4
print("Hasil Kurang set1 - set2:", getKurang2(set1, set2))  # 6 - 15 = -9

# O(1) - Constant Time
def get_first_element(arr):
    return arr[0]

# O(n) - Linear Time
def print_elements(arr):
    for item in arr:
        print(item)

# O(n^2) - Quadratic Time
def print_pairs(arr):
    for i in arr:
        for j in arr:
            print(i, j)

# O(log n) - Logarithmic Time (binary search)
def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1